### PR TITLE
Remove max version constraint on activemodel

### PR DESCRIPTION
**Pull request by quaelin**
User Service uses this gem, and I want to upgrade it to newer Rails version...

### CODE REVIEW

**Comment by mdimas** [comment]
I'm not positive this will work with ActiveModel 5.0. Have you tested it out with this branch in user_service?

**Comment by mdimas** [comment]
We might have to make a 5.0 branch of this validator.

**Comment by quaelin** [comment]
I haven't tested it yet, no.  Will do...

**Comment by quaelin** [comment]
I've tagged this as `2.3.0-rails5` for testing.

**Pull request closed without merging**
